docs(recipes): "profile.js --serial ${file}" error
`profile.js` expects `${file}` argument before other options like `--serial`. 

As documented it errors:

```bash
profile.js --serial ./test.js

profile.js:69
	throw new Error('Specify a test file');
	^

Error: Specify a test file
...
```