Cast test context to correct type.
When using `ava@1.0.0-beta.3` with `typescript@2.7.1`, the provided documentation fails to compile properly with an error that the type is not assignable. eg.
```
error TS2322: Type 'TestInterface<{}>' is not assignable to type 'TestInterface<{ foo: 'bar'; }>'.
  Type '{}' is not assignable to type '{ foo: 'bar'; }'.
    Property 'server' is missing in type '{}'.
```

This change casts the test object from Ava to the correctly paramaterized `TestInterface`.