resolveCwd doesn't work when use ava from an npm linked project
A common senario:
Project A depends on ava. Project B depends on project A. In Project A, call `npm link`. In project B, call `npm link ProjectA`. Now in project B tests are broken because resolveCwd cannot find ts-node/register:
```
Error: Could not resolve required module ’ts-node/register’
```

However, nodejs's `require` can find it, and also `require.resolve`. And use `require.resolve` doesn't break in original setup of ava so i use `require.resolve`.

Also with `console.log` I noticed that this `resolveModules` only tries to resolve one module: `ts-node/register`. What is the purpose of this method?