Fixed: example test fails because label is missing
The getting started example contains a minor defect.  Ava requires a label, but the example given does not have one.

```
test('receive foo asynchronously', async t => {
	t.is(await fn(), 'foo');
});
```

Result:

```
$ npx ava ./src/test/testset.ts

  Uncaught exception in src\test\testset.ts

  (censored)\src\test\testset.ts:12

   11:
   12: test(async t => {
   13:   t.is(await fn(), 'foo');

  TypeError: Tests must have a title

  Object.<anonymous> (src/test/testset.ts:12:5)
  Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
  Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)
```